import React, { FormEvent, useEffect, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { BrowserRouter, Link, NavLink, Route, Routes, useNavigate, useParams } from 'react-router-dom'
import './styles.css'

type CP = { chargepointorigin: string; serial_number: string | null; status: string; last_heartbeat: string | null; connector_count: number; open_transactions: number; connected: boolean; firmware?: string }
type Log = { id: number; chargepointorigin: string; message_type: string; body: string; way: string; created_at: string }
const api = async <T,>(url: string, init?: RequestInit): Promise<T> => { const res = await fetch(url, { ...init, headers: { 'Content-Type': 'application/json', ...(init?.headers || {}) } }); if (!res.ok) throw new Error((await res.json().catch(() => ({ detail: res.statusText }))).detail); return res.json() }
const date = (v: string | null) => v ? new Date(v).toLocaleString('it-IT') : 'Mai'

function Layout({ children }: { children: React.ReactNode }) { return <div className="shell"><aside><div className="brand">⚡ OCPP Console</div><NavLink to="/" end>◉ Overview</NavLink><NavLink to="/charge-points">▣ Charge Points</NavLink><NavLink to="/logs">▤ Message Log</NavLink><div className="side-note">OCPP 1.6J<br />PostgreSQL live</div></aside><main>{children}</main></div> }
function Header({ title, children }: { title: string; children?: React.ReactNode }) { return <header><div><h1>{title}</h1><p>Central System Management</p></div>{children}</header> }
function Dashboard() { const [data, setData] = useState<any>(); useEffect(() => { const load = () => api<any>('/api/dashboard').then(setData).catch(console.error); load(); const x = setInterval(load, 10000); return () => clearInterval(x) }, []); if (!data) return <p>Caricamento…</p>; return <><Header title="Overview" /><section className="stats"><Stat label="Charge Points" value={data.chargepoints} /><Stat label="Online" value={data.online} accent /><Stat label="Transazioni aperte" value={data.open_transactions} /></section><section className="panel"><h2>Recent Activity</h2><LogTable logs={data.recent_activity} /></section></> }
function Stat({ label, value, accent }: { label: string; value: number; accent?: boolean }) { return <article className={'stat ' + (accent ? 'accent' : '')}><span>{label}</span><strong>{value}</strong></article> }
function ChargePoints() { const [items, setItems] = useState<CP[]>([]); const [open, setOpen] = useState(false); const [error, setError] = useState(''); const load = () => api<CP[]>('/api/charge-points').then(setItems).catch(e => setError(e.message)); useEffect(() => { load(); const x = setInterval(load, 10000); return () => clearInterval(x) }, []); return <><Header title="Charge Points"><button onClick={() => setOpen(true)}>+ Add Charge Point</button></Header>{error && <p className="error">{error}</p>}<div className="cards">{items.map(cp => <Link className="cp-card" key={cp.chargepointorigin} to={'/charge-points/' + encodeURIComponent(cp.chargepointorigin)}><div className="card-title"><span className={cp.connected ? 'online' : 'offline'}></span><b>{cp.chargepointorigin}</b></div><small>{cp.serial_number || 'Seriale non comunicato'}</small><p>{cp.status} · {cp.connector_count} connettori</p><footer>{cp.connected ? 'Connesso' : 'Offline'} · {date(cp.last_heartbeat)}</footer></Link>)}</div>{!items.length && !error && <p>Nessun Charge Point registrato.</p>}{open && <AddCP onClose={() => setOpen(false)} onCreated={() => { setOpen(false); load() }} />}</> }
function AddCP({ onClose, onCreated }: { onClose: () => void; onCreated: () => void }) { const [error, setError] = useState(''); const submit = async (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const f = new FormData(e.currentTarget); try { await api('/api/charge-points', { method: 'POST', body: JSON.stringify(Object.fromEntries(f)) }); onCreated() } catch (e: any) { setError(e.message) } }; return <div className="modal"><form onSubmit={submit}><h2>Add Charge Point</h2><input name="identity" placeholder="ID OCPP" required /><input name="serial_number" placeholder="Seriale" required /><input name="vendor" placeholder="Vendor" required /><input name="model" placeholder="Modello" required />{error && <p className="error">{error}</p>}<div className="actions"><button type="button" className="secondary" onClick={onClose}>Annulla</button><button>Crea CP</button></div></form></div> }
function Detail() { const { identity = '' } = useParams(); const [data, setData] = useState<any>(); const [error, setError] = useState(''); const load = () => api<any>('/api/charge-points/' + encodeURIComponent(identity)).then(setData).catch(e => setError(e.message)); useEffect(() => { load(); const x = setInterval(load, 10000); return () => clearInterval(x) }, [identity]); if (error) return <p className="error">{error}</p>; if (!data) return <p>Caricamento…</p>; const cp = data.chargepoint; return <><Header title={cp.chargepointorigin}><Link className="back" to="/charge-points">← Charge Points</Link></Header><section className="detail-grid"><article className="panel"><h2>Stato</h2><p><span className={data.connected ? 'online' : 'offline'}></span> {data.connected ? 'Connesso' : 'Offline'}</p><p>Seriale: <b>{cp.serial_number || '—'}</b></p><p>Ultimo heartbeat: {date(cp.last_heartbeat)}</p><h3>Connettori</h3>{data.connectors.map((c: any) => <p key={c.id}>#{c.connector_id} — {c.status} ({c.errorCode || 'NoError'})</p>)}</article><Commands identity={identity} transactions={data.transactions} onDone={load} /></section><section className="panel"><h2>Transazioni</h2><table><thead><tr><th>ID</th><th>RFID</th><th>Connettore</th><th>Avvio</th><th>Stop</th><th>Motivo OCPP</th></tr></thead><tbody>{data.transactions.map((t: any) => <tr key={t.id}><td>{t.transaction_id}</td><td>{t.id_tag}</td><td>{t.ocpp_connector_id}</td><td>{t.start_reason || 'LocalStart'}</td><td>{t.stop_reason || '—'}</td><td>{t.reason || '—'}</td></tr>)}</tbody></table></section></> }
function Commands({ identity, transactions, onDone }: { identity: string; transactions: any[]; onDone: () => void }) { const [msg, setMsg] = useState(''); const start = async (e: FormEvent<HTMLFormElement>) => { e.preventDefault(); const f = new FormData(e.currentTarget); try { const r: any = await api('/api/charge-points/' + encodeURIComponent(identity) + '/remote-start', { method: 'POST', body: JSON.stringify({ id_tag: f.get('id_tag'), connector_id: Number(f.get('connector_id')) }) }); setMsg('Remote start: ' + r.status); onDone() } catch (e: any) { setMsg(e.message) } }; const stop = async (id: number) => { try { const r: any = await api('/api/charge-points/' + encodeURIComponent(identity) + '/remote-stop', { method: 'POST', body: JSON.stringify({ transaction_id: id }) }); setMsg('Remote stop: ' + r.status); onDone() } catch (e: any) { setMsg(e.message) } }; return <article className="panel"><h2>Azioni OCPP</h2><form onSubmit={start}><input name="id_tag" placeholder="RFID" required /><input name="connector_id" type="number" min="1" defaultValue="1" required /><button>◉ Remote Start</button></form><h3>Transazioni aperte</h3>{transactions.filter(t => !t.ts_stop).map(t => <button className="danger" key={t.id} onClick={() => stop(t.transaction_id)}>■ Stop #{t.transaction_id}</button>)}<p>{msg}</p></article> }
function Logs() { const [items, setItems] = useState<Log[]>([]); const [total, setTotal] = useState(0); const [filters, setFilters] = useState({ identity: '', action: '', way: '', search: '' }); const load = () => { const p = new URLSearchParams(Object.entries(filters).filter(([, v]) => v)); api<any>('/api/logs?' + p).then(d => { setItems(d.items); setTotal(d.total) }).catch(console.error) }; useEffect(load, []); return <><Header title="Message Log" /><form className="filters" onSubmit={e => { e.preventDefault(); load() }}><input placeholder="Charge Point" value={filters.identity} onChange={e => setFilters({ ...filters, identity: e.target.value })} /><input placeholder="Action" value={filters.action} onChange={e => setFilters({ ...filters, action: e.target.value })} /><select value={filters.way} onChange={e => setFilters({ ...filters, way: e.target.value })}><option value="">Tutte le direzioni</option><option value="incoming">Incoming</option><option value="outgoing">Outgoing</option></select><input placeholder="Cerca nel frame" value={filters.search} onChange={e => setFilters({ ...filters, search: e.target.value })} /><button>Filtra</button></form><p>{total} messaggi</p><section className="panel"><LogTable logs={items} /></section></> }
function LogTable({ logs }: { logs: Log[] }) { return <table className="logs"><thead><tr><th>Ora</th><th>CP</th><th>Action</th><th>Dir.</th><th>Frame</th></tr></thead><tbody>{logs.map(l => <tr key={l.id}><td>{date(l.created_at)}</td><td>{l.chargepointorigin}</td><td>{l.message_type}</td><td>{l.way}</td><td><code>{l.body}</code></td></tr>)}</tbody></table> }
function App() { return <BrowserRouter><Layout><Routes><Route path="/" element={<Dashboard />} /><Route path="/charge-points" element={<ChargePoints />} /><Route path="/charge-points/:identity" element={<Detail />} /><Route path="/logs" element={<Logs />} /></Routes></Layout></BrowserRouter> }; createRoot(document.getElementById('root')!).render(<App />)
